export const defaultTheme = {
  useAvatar: false,
  avatarImage: "",
  header: {
    visible: true,
    fontFamily: "UhBeeJJIBBABBA",
    letterSpacing: "0em",
    lineHeight: "110%",
    color: "rgba(0,0,0,1)",
    colorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 1,
    },
    useTextShadow: false,
    textShadow: "unset",
    textShadowProps: {
      x: 1,
      y: 1,
      blur: 2,
      rgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0.5,
      },
    },
    backgroundColor: "rgba(0,0,0,0)",
    backgroundColorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 0,
    },
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useBoxShadow: false,
    boxShadow: "unset",
    boxShadowProps: {
      x: 1,
      y: 1,
      blur: 2,
      rgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0.5,
      },
    },
    borderRadius: "0em",
    useBorder: false,
    borderWidth: "1.5px",
    borderStyle: "none",
    borderColor: "rgba(211,211,211,1)",
    borderColorRgba: {
      r: 211,
      g: 211,
      b: 211,
      a: 1,
    },
    useBorderImage: false,
    borderImageSource: "none",
    borderImageWidth: "1em 1em 1em 1em",
    borderImageSlice: "30px 30px 30px 30px",
    borderImageRepeat: "stretch stretch",
    borderImageOutset: "0 0 0 0",
    //   borderImageSlice: "27 27 27 27",
    //   borderImageWidth: "20px 20px 20px 20px",
    //   borderImageOutset: "0 0 0 0",
    //   borderImageRepeat: "stretch stretch",
    //   borderImageSource: 'url("https://mdn.mozillademos.org/files/6011/border-image-3.png")'
  },
  question: {
    visible: true,
    fontFamily: "Pretendard-Regular",
    letterSpacing: "0em",
    lineHeight: "110%",
    color: "rgba(0,0,0,1)",
    colorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 1,
    },
    useTextShadow: false,
    textShadow: "unset",
    textShadowProps: {
      x: 1,
      y: 1,
      blur: 2,
      rgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0.5,
      },
    },
    backgroundColor: "rgba(234, 234, 255, .5)",
    backgroundColorRgba: {
      r: 234,
      g: 234,
      b: 255,
      a: 0.5,
    },
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useBoxShadow: true,
    boxShadow: "1px 5px 0px rgba(144, 145, 200, .77)",
    boxShadowProps: {
      x: 1,
      y: 5,
      blur: 0,
      rgba: {
        r: 144,
        g: 145,
        b: 200,
        a: 0.77,
      },
    },
    borderRadius: "1.5em",
    useBorder: true,
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "rgba(198,198,211,1)",
    borderColorRgba: {
      r: 198,
      g: 198,
      b: 211,
      a: 1,
    },
  },
  answer: {
    fontFamily: "Pretendard-Light",
    letterSpacing: "0em",
    lineHeight: "110%",
    color: "rgba(0,0,0,1)",
    colorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 1,
    },
    useTextShadow: false,
    textShadow: "unset",
    textShadowProps: {
      x: 1,
      y: 1,
      blur: 2,
      rgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0.5,
      },
    },
    backgroundColor: "rgba(0,0,0,0)",
    backgroundColorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 0,
    },
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useBoxShadow: true,
    boxShadow: "1px 5px 0px rgba(206, 206, 206, .77)",
    boxShadowProps: {
      x: 1,
      y: 5,
      blur: 0,
      rgba: {
        r: 206,
        g: 206,
        b: 206,
        a: 0.77,
      },
    },
    borderRadius: "1.5em",
    useBorder: true,
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "rgba(211,211,211,1)",
    borderColorRgba: {
      r: 211,
      g: 211,
      b: 211,
      a: 1,
    },
  },
  button: {
    iconButton: false,
    fontFamily: "Pretendard-Regular",
    letterSpacing: "0em",
    lineHeight: "110%",
    color: "rgba(0,0,0,1)",
    colorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 1,
    },
    useTextShadow: false,
    textShadow: "unset",
    textShadowProps: {
      x: 1,
      y: 1,
      blur: 2,
      rgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0.5,
      },
    },
    backgroundColor: "rgba(0,0,0,0)",
    backgroundColorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 0,
    },
    backgroundImage: "none",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useBoxShadow: true,
    boxShadow: "1px 3px 0px rgba(206, 206, 206, .77)",
    boxShadowProps: {
      x: 1,
      y: 3,
      blur: 0,
      rgba: {
        r: 206,
        g: 206,
        b: 206,
        a: 0.77,
      },
    },
    borderRadius: ".8em",
    useBorder: true,
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "rgba(211,211,211,1)",
    borderColorRgba: {
      r: 211,
      g: 211,
      b: 211,
      a: 1,
    },
  },
  avatar: {
    iconButton: false,
    fontFamily: "Pretendard-Regular",
    letterSpacing: "0em",
    lineHeight: "110%",
    color: "rgba(0,0,0,1)",
    colorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 1,
    },
    useTextShadow: false,
    textShadow: "unset",
    textShadowProps: {
      x: 1,
      y: 1,
      blur: 2,
      rgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0.5,
      },
    },
    backgroundColor: "rgba(0,0,0,0)",
    backgroundColorRgba: {
      r: 0,
      g: 0,
      b: 0,
      a: 0,
    },
    backgroundImage: "url('https://pbs.twimg.com/profile_images/1298450223438557186/DVjxUmRS_400x400.jpg')",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    useBoxShadow: false,
    boxShadow: "unset",
    boxShadowProps: {
      x: 1,
      y: 3,
      blur: 0,
      rgba: {
        r: 206,
        g: 206,
        b: 206,
        a: 0.77,
      },
    },
    borderRadius: "4em",
    useBorder: false,
    borderWidth: "1.5px",
    borderStyle: "none",
    borderColor: "rgba(211,211,211,1)",
    borderColorRgba: {
      r: 211,
      g: 211,
      b: 211,
      a: 1,
    },
  },
};
