export const defaultTheme = {
    header:{
      visible: true,
      fontFamily: "UhBeeJJIBBABBA",
      color: "rgba(0,0,0,1)",
      colorRgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 1,
      },
      useTextShadow: false,
      textShadow:"unset",
      textShadowProps:{
          x: 1,
          y: 1,
          blur: 2,
          rgba: {
            r: 0,
            g: 0,
            b: 0,
            a: 0.5,
        },
      },
      backgroundColor: "rgba(0,0,0,0)",
      backgroundColorRgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0,
      },
    //   borderImageSlice: "27 27 27 27",
    //   borderImageWidth: "20px 20px 20px 20px",
    //   borderImageOutset: "0 0 0 0",
    //   borderImageRepeat: "stretch stretch",
    //   borderImageSource: 'url("https://mdn.mozillademos.org/files/6011/border-image-3.png")'
    },
    question:{
      visible: true,
      fontFamily: "Pretendard-Regular",
      color: "rgba(0,0,0,1)",
      colorRgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 1,
      },
      useTextShadow: false,
      textShadow:"unset",
      textShadowProps:{
        x: 1,
        y: 1,
        blur: 2,
        rgba: {
          r: 0,
          g: 0,
          b: 0,
          a: 0.5,
      },
    },
      backgroundColor: "rgba(234, 234, 255, .5)",
      backgroundColorRgba: {
        r: 234,
        g: 234,
        b: 255,
        a: .5,
      },
    //     borderImageSlice: "27 27 27 27",
    //   borderImageWidth: "20px 20px 20px 20px",
    //   borderImageOutset: "0 0 0 0",
    //   borderImageRepeat: "stretch stretch",
    //   borderImageSource: 'url("https://mdn.mozillademos.org/files/6011/border-image-3.png")'
    },
    answer:{
      fontFamily: "Pretendard-Regular",
      color: "rgba(0,0,0,1)",
      colorRgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 1,
      },
      useTextShadow: false,
      textShadow:"unset",
      textShadowProps:{
        x: 1,
        y: 1,
        blur: 2,
        rgba: {
          r: 0,
          g: 0,
          b: 0,
          a: 0.5,
      },
    },
      backgroundColor: "rgba(0,0,0,0)",
      backgroundColorRgba: {
        r: 0,
        g: 0,
        b: 0,
        a: 0,
      }
    },
    button:{
        iconButton: false,
        fontFamily: "Pretendard-Regular",
        color: "rgba(0,0,0,1)",
        colorRgba: {
          r: 0,
          g: 0,
          b: 0,
          a: 1,
        },
      useTextShadow: false,
      textShadow:"unset",
        textShadowProps:{
            x: 1,
            y: 1,
            blur: 2,
            rgba: {
              r: 0,
              g: 0,
              b: 0,
              a: 0.5,
          },
        },
        backgroundColor: "rgba(0,0,0,0)",
        backgroundColorRgba: {
          r: 0,
          g: 0,
          b: 0,
          a: 0,
        }
      },
  }